name: acgnhub
description: ACGNhub - Anime, Comic, Game, Novel aggregation app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  flutter_cache_manager: ^3.4.1
  html: ^0.15.5
  xml: ^6.5.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.4
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  webview_windows:
    git:
      url: https://github.com/Predidit/flutter-webview-windows.git
  media_kit: ^1.2.0
  media_kit_video: ^1.2.0
  media_kit_libs_windows_video: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rules/
    - assets/anime_seed.json