name: libiko_server
description: Libiko account and sync backend
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.6.0
dependencies:
  bcrypt: ^1.2.0
  dart_jsonwebtoken: ^3.4.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite3: ^2.9.4
dev_dependencies:
  test: ^1.31.0
